/*
  # Add AI Description Column to Photos Table

  1. Changes
    - Add `ai_description` column to `photos` table
      - Type: text
      - Default: empty string
      - Purpose: Store AI-generated image descriptions from OpenAI

  2. Notes
    - This column will store descriptions generated by OpenAI Vision API
    - Users will see both their own description and the AI description in the gallery
    - No changes to existing RLS policies needed
*/

-- Add ai_description column to photos table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'photos' AND column_name = 'ai_description'
  ) THEN
    ALTER TABLE photos ADD COLUMN ai_description text DEFAULT '';
  END IF;
END $$;
