/*
  # Add AI Description Column to Videos Table

  1. Changes
    - Add `ai_description` column to `videos` table
      - Type: text
      - Default: empty string
      - Purpose: Store AI-generated video descriptions from OpenAI Vision API

  2. Notes
    - This column will store descriptions generated by analyzing a frame extracted from the video (at 60-second mark)
    - For videos shorter than 60 seconds, the frame will be extracted from the middle of the video
    - Users will see both their own description and the AI description in the gallery
    - No changes to existing RLS policies needed
    - Mirrors the ai_description column already present in the photos table
*/

-- Add ai_description column to videos table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'videos' AND column_name = 'ai_description'
  ) THEN
    ALTER TABLE videos ADD COLUMN ai_description text DEFAULT '';
  END IF;
END $$;